/* BootKit 1.0.0 — dependency-free startup state machine and browser game mode.
   Standard contract: ordered run(code,label,fn), READY handoff, engine hooks,
   first-frame gate, bounded reports. Branding and renderer list are injected.
   This file uses ES5 syntax so it can report an unsupported engine runtime.
   A blocked browser/driver thread cannot be preempted by a JavaScript timer.
   Checkpoints are written BEFORE work so an interrupted launch can be reported.
*/
(function (global) {
 'use strict';
 var VERSION='1.0.0', SCHEMA='bootkit.report.v1';
 function el(id){return document.getElementById(id);}
 function text(id,v){var e=el(id);if(e)e.textContent=String(v==null?'Unavailable':v);}
 function now(){return global.performance&&performance.now?performance.now():Date.now();}
 function scrub(v){return String(v==null?'':v).replace(/(?:file|content):\/\/[^\s)]+/g,'[local-file]').replace(/https?:\/\/[^\s)]+/g,'[page]').slice(0,6000);}
 function own(o,k){return Object.prototype.hasOwnProperty.call(o,k);}
 function error(code,message){var e=new Error(message);e.bootCode=code;return e;}
 function value(name){try{var m=new RegExp('(?:[?#&])'+name+'=([^&#]*)').exec(location.search+'&'+location.hash);return m?decodeURIComponent(m[1]):null;}catch(e){return null;}}
 function makeView(host,config){host.innerHTML='<div class="sb-card"><header id="sb-header"><div class="sb-top"><span class="sb-over" id="sb-brand"></span><span class="sb-badge">BOOT / 1.0</span></div><h1 id="sb-title">System startup</h1><p id="sb-subtitle">Checking this device before the game loads.</p></header><p id="sb-previous" hidden></p><div id="sb-statusBlock"><div id="sb-stage" role="status" aria-live="polite">B00 / INIT</div><progress id="sb-progress" max="100" value="0" aria-label="Completed startup stages"></progress><div id="sb-progressText">System checks · 0%</div><p id="sb-detail">Starting the diagnostic recorder.</p></div><dl class="sb-facts"><dt>Game</dt><dd id="sb-game"></dd><dt>Build</dt><dd id="sb-build"></dd><dt>Platform</dt><dd id="sb-platform">Checking</dd><dt>Browser</dt><dd id="sb-browser">Checking</dd><dt>Renderer</dt><dd id="sb-renderer">Not selected</dd><dt>Adapter</dt><dd id="sb-adapter">Not reported yet</dd><dt>Report</dt><dd id="sb-id"></dd></dl><div id="sb-logWrap"><ol id="sb-log" class="sb-log" aria-label="Startup stages"></ol><details><summary>Optional features and limits</summary><div id="sb-optionalList">Checking</div></details></div><section id="sb-failure" role="alert" hidden><strong id="sb-errorCode"></strong><p id="sb-errorMessage"></p><p class="sb-small">Startup has stopped. Keep this screen for a screenshot. Copy or save the report before you retry.</p></section><section id="sb-ready" class="sb-ready-box" hidden><p><b>Graphics checks passed.</b> Choose how to play.</p><div class="sb-options"><label>Orientation <select id="sb-orientation"><option value="auto">Auto rotate</option><option value="landscape">Landscape</option><option value="portrait">Portrait</option></select></label><label><input id="sb-wake" type="checkbox" checked> Keep screen awake</label></div><div class="sb-actions sb-launch"><button id="sb-startGame" class="sb-primary">Start in game mode</button><button id="sb-startWindow">Start in window</button></div><p class="sb-small" id="sb-modeNote">Game mode requests fullscreen and reduces page gestures. System gestures, notifications, and app switching remain under device control.</p></section><footer id="sb-actionFooter"><div class="sb-actions"><button id="sb-copy">Copy report</button><button id="sb-save">Save report</button><button id="sb-retry" hidden>Retry startup</button><button id="sb-stop">Stop startup</button></div><p class="sb-small" id="sb-footer">Local diagnostics only. Nothing is uploaded.</p></footer></div>';
  text('sb-brand',config.name+' / SYSTEM START');text('sb-game',config.name+' '+config.version);text('sb-build',config.build);
 }
 function Boot(config){
  this.config=config;this.startedAt=now();this.failed=false;this.loaded=false;this.running=false;this.busy=false;this.phase='checks';this.current='B00';this.serial=0;this.hooks={};this.pending=[];this.rows={};this.engineStarted=false;this.checkpointKey='bootkit.last.'+(config.storageId||config.name);this.tests=value('bootTest')==='1';this.inject=this.tests?value('bootFail'):null;this.delay=this.tests?Number(value('bootDelay'))||0:0;
  this.report={schema:SCHEMA,bootVersion:VERSION,game:{name:config.name,version:config.version,build:config.build},id:'BT-'+new Date().toISOString().replace(/[-:.TZ]/g,'').slice(0,17),createdAt:new Date().toISOString(),status:'checking',stage:'B00',platform:{},renderer:{selected:null,attempts:[]},capabilities:{},stages:[],events:[],errors:[],warnings:[],tests:this.tests};
  this.host=el(config.host||'sb-root');makeView(this.host,config);text('sb-id',this.report.id);this.previous=null;try{this.previous=JSON.parse(sessionStorage.getItem(this.checkpointKey)||'null');}catch(e){}
  if(this.previous&&['working','failed'].indexOf(this.previous.status)>=0)text('sb-previous','Previous attempt: '+this.previous.stage+' / '+(this.previous.failure||'did not finish; cause unknown')+'. This is a new attempt.');else el('sb-previous').hidden=true;
  if(this.previous&&['working','failed'].indexOf(this.previous.status)>=0)el('sb-previous').hidden=false;
  this.report.previousAttempt=this.previous;this.bind();this.screen=new ScreenMode(this);this.record('info','B00','Recorder ready');
 }
 Boot.prototype.bind=function(){var b=this;el('sb-copy').onclick=function(){b.copy();};el('sb-save').onclick=function(){b.save();};el('sb-retry').onclick=function(){b.screen.leave('Retry');location.reload();};el('sb-stop').onclick=function(){b.fail('BOOT-STOP','Startup stopped by the player.');};el('sb-startGame').onclick=function(){b.launch(true);};el('sb-startWindow').onclick=function(){b.launch(false);};
  global.addEventListener('error',function(e){if(!e.message&&!e.error)return;b.fail(b.running?'RUN-JS':'BOOT-JS',e.error||e.message,{line:e.lineno||null,column:e.colno||null});});
  global.addEventListener('unhandledrejection',function(e){b.fail(b.running?'RUN-ASYNC':'BOOT-ASYNC',e.reason||'An asynchronous task failed.');});
  document.addEventListener('securitypolicyviolation',function(e){if(b.busy&&!b.running)b.fail('BOOT-POLICY','The page policy blocked startup: '+e.violatedDirective);});
  global.addEventListener('pagehide',function(){if(!b.failed&&b.running)b.checkpoint('closed');});
 };
 Boot.prototype.checkpoint=function(status){var c={id:this.report.id,build:this.config.build,stage:this.current,status:status,at:new Date().toISOString(),failure:this.report.failure?this.report.failure.code:null};try{sessionStorage.setItem(this.checkpointKey,JSON.stringify(c));}catch(e){this.report.capabilities.sessionStorage=false;}};
 Boot.prototype.record=function(level,code,message,data){var r={ms:Math.round(now()-this.startedAt),stage:this.current,level:level,code:code,message:scrub(message)};if(data)r.data=data;this.report.events.push(r);if(this.report.events.length>256)this.report.events.shift();if(level==='warn'){this.report.warnings.push(r);if(this.report.warnings.length>64)this.report.warnings.shift();}return r;};
 Boot.prototype.detail=function(message){text('sb-detail',message);};
 Boot.prototype.row=function(s){var r=this.rows[s.code];if(!r){r=document.createElement('li');var a=document.createElement('span'),b=document.createElement('span'),c=document.createElement('span');a.className='sb-code';c.className='sb-state';r.appendChild(a);r.appendChild(b);r.appendChild(c);el('sb-log').appendChild(r);this.rows[s.code]=r;}r.children[0].textContent=s.code;r.children[1].textContent=s.label;r.children[2].textContent=s.status.toUpperCase();r.children[2].className='sb-state '+(s.status==='warn'?'sb-warn':s.status==='failed'?'sb-error':'');var log=el('sb-log');log.scrollTop=log.scrollHeight;};
 Boot.prototype.progress=function(){var stages=this.report.stages.filter(function(s){return s.phase===this.phase;},this),done=stages.filter(function(s){return s.status==='pass'||s.status==='warn';}).length,total=this.phase==='checks'?6:8,pct=Math.min(100,Math.round(done/total*100));el('sb-progress').value=pct;text('sb-progressText',(this.phase==='checks'?'System checks':'Engine start')+' · '+pct+'% · '+done+' / '+total+' stages');};
 Boot.prototype.run=function(code,label,work,timeout){var b=this;if(this.failed)return Promise.reject(error('BOOT-CANCELLED','Startup already stopped.'));var order=['B10','B20','B30','B40','B50','B60','L10','L20','L30','L40','L50','L60','L70','L80'];if(code!==order[this.report.stages.length]){var bad=error('BOOT-ORDER','Expected startup stage '+order[this.report.stages.length]+', not '+code+'.');this.fail(bad.bootCode,bad);return Promise.reject(bad);}var s={code:code,label:label,phase:this.phase,status:'work',startMs:Math.round(now()-this.startedAt)};this.current=code;this.report.stage=code;this.busy=true;this.report.stages.push(s);this.report.status='working';this.checkpoint('working');text('sb-stage',code+' / '+label.toUpperCase());this.detail('Please wait. This stage must finish before the next one starts.');this.row(s);this.progress();
  return new Promise(function(resolve,reject){var settled=false,timer=null,slow=null;function finish(err,result){if(settled)return;settled=true;clearTimeout(timer);clearTimeout(slow);s.durationMs=Math.round(now()-b.startedAt-s.startMs);if(err||b.failed){s.status='failed';b.row(s);var problem=err||error('BOOT-CANCELLED','Startup stopped.');if(!b.failed)b.fail(problem.bootCode||code+'-FAIL',problem);reject(problem);return;}s.status='pass';b.busy=false;b.row(s);b.progress();b.record('info',code,label+' complete',{durationMs:s.durationMs});resolve(result);}
   timer=setTimeout(function(){finish(error(code+'-TIME','This startup stage exceeded '+Math.round((timeout||30000)/1000)+' seconds.'));},timeout||30000);
   slow=setTimeout(function(){if(!settled&&!b.failed)b.detail('This stage is taking longer than expected. You can save a report or stop startup.');},5000);
   setTimeout(function(){if(b.failed){finish(error('BOOT-CANCELLED','Startup stopped.'));return;}if(b.inject===code){finish(error(code+'-TEST','Intentional test failure at '+code+'. No real device fault.'));return;}try{var r=work();if(r&&typeof r.then==='function')r.then(function(v){finish(null,v);},finish);else finish(null,r);}catch(e){finish(e);}},Math.max(25,b.delay));
  });
 };
 Boot.prototype.optional=function(code,message){this.record('warn',code,message);};
 Boot.prototype.fail=function(code,reason,extra){var ex=reason instanceof Error?reason:new Error(String(reason||'Unknown startup error')),entry={code:code,stage:this.current,phase:this.phase,ms:Math.round(now()-this.startedAt),name:ex.name,message:scrub(ex.message),stack:scrub(ex.stack||''),extra:extra||null};this.report.errors.push(entry);if(this.report.errors.length>64)this.report.errors.shift();if(this.failed)return;
  this.failed=true;this.running=false;this.report.status='failed';this.report.failure=entry;this.report.failedAt=new Date().toISOString();this.serial++;this.checkpoint('failed');this.record('error',code,ex.message);document.documentElement.classList.add('sb-failed');document.documentElement.classList.remove('sb-game-focus');this.host.hidden=false;if(el('sb-mode'))el('sb-mode').hidden=true;if(el('sb-report'))el('sb-report').hidden=true;if(el('sb-backGame'))el('sb-backGame').hidden=true;el('sb-failure').hidden=false;el('sb-ready').hidden=true;el('sb-stop').hidden=true;el('sb-retry').hidden=false;text('sb-title','Startup stopped');if(this.phase==='runtime')text('sb-title','Game stopped');text('sb-subtitle','The diagnostic screen is still available.');text('sb-stage',this.current+' / STOPPED');text('sb-errorCode',code);text('sb-errorMessage',scrub(ex.message).slice(0,650));this.detail('Report '+this.report.id+' · stage '+this.current);var last=this.report.stages[this.report.stages.length-1];if(last&&last.status==='work'){last.status='failed';this.row(last);}try{if(this.hooks.stop)this.hooks.stop(ex);}catch(e){}if(this.screen)this.screen.leave('Error');
 };
 Boot.prototype.snapshot=function(){var r=JSON.parse(JSON.stringify(this.report));r.savedAt=new Date().toISOString();r.screenMode=this.screen.snapshot();r.elapsedMs=Math.round(now()-this.startedAt);try{if(this.hooks.info)r.gameState=this.hooks.info();}catch(e){r.gameState={error:scrub(e.message)};}return r;};
 Boot.prototype.json=function(){return JSON.stringify(this.snapshot(),null,2);};
 Boot.prototype.save=function(){try{var data=this.json(),blob=new Blob([data],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=this.report.id+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},60000);text('sb-footer','Report prepared. Use Copy report if this browser blocks downloads.');}catch(e){this.showReport('Select the report text and copy it.');}};
 Boot.prototype.showReport=function(message){var panel=el('sb-report'),b=this;if(!panel){panel=document.createElement('section');panel.id='sb-report';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.innerHTML='<div class="sb-card"><div class="sb-top"><h1>Startup report</h1><button class="sb-close" id="sb-reportClose">Close</button></div><p id="sb-copyHelp"></p><textarea id="sb-reportText" readonly aria-label="Startup report JSON"></textarea><button id="sb-select">Select all</button></div>';document.body.appendChild(panel);el('sb-reportClose').onclick=function(){panel.hidden=true;};el('sb-select').onclick=function(){el('sb-reportText').focus();el('sb-reportText').select();};}panel.hidden=false;el('sb-reportText').value=this.json();text('sb-copyHelp',message||'Nothing is sent automatically. Select and copy this text, or take a screenshot of the startup screen.');};
 Boot.prototype.copy=function(){var b=this,data=this.json();if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(data).then(function(){text('sb-footer','Report copied.');b.screen.notice('Startup report copied.');},function(){b.showReport('Clipboard access was blocked. Select the text and copy it.');});}else this.showReport('Clipboard access is unavailable. Select the text and copy it.');};
 Boot.prototype.start=function(){var b=this;if(!global.Promise){this.fail('SYS-PROMISE','This browser does not provide the JavaScript runtime needed by the game.');return;}
  this.run('B10','Platform',function(){var p=b.report.platform;p.userAgent=navigator.userAgent;p.platform=navigator.userAgentData&&navigator.userAgentData.platform||navigator.platform||'Not reported';p.touchPoints=navigator.maxTouchPoints||0;p.primaryPointer=global.matchMedia&&matchMedia('(pointer:coarse)').matches?'coarse':'fine';p.protocol=location.protocol;p.secureContext=!!global.isSecureContext;p.viewport=[innerWidth,innerHeight];p.pixelRatio=global.devicePixelRatio||1;p.logicalProcessors=navigator.hardwareConcurrency||null;p.deviceMemoryGiB=navigator.deviceMemory||null;
   var ua=navigator.userAgent,bm=/(EdgA?|EdgiOS|Firefox|FxiOS|CriOS|Chrome|Version)\/([\d.]+)/.exec(ua);p.browser=bm?((bm[1]==='Version'?'Safari':bm[1])+' '+bm[2]):'Not reported';text('sb-browser',p.browser);var override=value('ui');b.mobile=override==='mobile'||override!=='desktop'&&p.touchPoints>0&&p.primaryPointer==='coarse';document.documentElement.classList.toggle('touch-ui',b.mobile);p.interface=b.mobile?'mobile':'desktop';text('sb-platform',p.platform+' / '+p.interface+' / '+innerWidth+' × '+innerHeight);return true;
  }).then(function(){return b.run('B20','Required APIs',function(){var required={typedArrays:!!global.Float32Array,promise:!!global.Promise,animationFrame:!!global.requestAnimationFrame,performance:!!(global.performance&&performance.now),pointerEvents:!!global.PointerEvent,pointerCapture:!!Element.prototype.setPointerCapture,modernObjects:!!(Object.entries&&Object.fromEntries&&Array.prototype.flatMap),collections:!!(global.Map&&global.Set&&global.WeakMap),urlParameters:!!global.URLSearchParams,canvas:!!document.createElement('canvas').getContext};try{required.canvas2d=!!document.createElement('canvas').getContext('2d');}catch(e){required.canvas2d=false;}b.report.capabilities.required=required;var missing=[];for(var k in required)if(own(required,k)&&!required[k])missing.push(k);if(missing.length)throw error('SYS-API','Required browser features are missing: '+missing.join(', '));if(!Object.hasOwn)Object.hasOwn=function(o,k){return own(o,k);};if(!b.config.renderers||!b.config.renderers.length)throw error('GFX-CONFIG','The game has not registered a rendering backend.');});
  }).then(function(){return b.run('B30','Graphics backend',function(){return b.selectRenderer();},Math.max(10000,(b.config.renderers||[]).length*5500));
  }).then(function(){return b.run('B40','Graphics limits',function(){b.checkLimits();});
  }).then(function(){return b.run('B50','Graphics self-test',function(){return b.probe();},12000);
  }).then(function(){return b.run('B60','Optional services',function(){b.optionalChecks();});
  }).then(function(){if(b.failed)return;b.current='READY';b.report.stage='READY';b.report.status='ready';b.busy=false;b.checkpoint('ready');text('sb-stage','READY / GRAPHICS CHECKS PASSED');text('sb-title','Ready to start');text('sb-subtitle','The game interface and simulation are not loaded yet.');b.detail('Select a start mode. The engine will load next.');el('sb-ready').hidden=false;el('sb-stop').hidden=true;if(!b.screen.supported())text('sb-modeNote','Fullscreen is not available in this browser. Game mode can still reduce page gestures. System controls and app switching remain available.');b.progress();
  }).catch(function(e){if(!b.failed)b.fail(e.bootCode||'BOOT-FAIL',e);});
 };
 Boot.prototype.selectRenderer=function(){var b=this,index=0;this.report.capabilities.webgpuAPI=!!navigator.gpu;this.report.renderer.supportedByGame=this.config.renderers.map(function(r){return r.id;});var compatibleGPU=this.report.renderer.supportedByGame.indexOf('webgpu')>=0;if(navigator.gpu&&!compatibleGPU)this.record('info','GFX-SKIP','WebGPU API exposed; no WebGPU renderer is included in this game.');
  function release(h){try{if(h.dispose)h.dispose();else if(h.device)h.device.destroy();else if(h.id==='webgl2'||h.id==='webgl'){var e=h.context.getExtension('WEBGL_lose_context');if(e)e.loseContext();}}catch(e){}}
  function candidate(work,ms){return new Promise(function(resolve,reject){var done=false,timer=setTimeout(function(){done=true;reject(error('GFX-TIME','Renderer candidate did not respond. Trying the next registered backend.'));},ms);Promise.resolve().then(work).then(function(h){if(done||b.failed){release(h);return;}done=true;clearTimeout(timer);resolve(h);},function(e){if(done)return;done=true;clearTimeout(timer);reject(e);});});}
  function next(){if(b.failed)throw error('BOOT-CANCELLED','Renderer selection stopped.');if(index>=b.config.renderers.length)throw error('GFX-NONE','No compatible renderer initialized. This game includes: '+b.report.renderer.supportedByGame.join(', ')+'. Enable graphics acceleration or use a compatible browser.');var spec=b.config.renderers[index++],canvas=document.createElement('canvas');canvas.width=canvas.height=16;canvas.hidden=true;var attempt={backend:spec.id,status:'trying'};b.report.renderer.attempts.push(attempt);return candidate(function(){if(spec.initialize)return spec.initialize(canvas,b);if(spec.id==='webgl2'||spec.id==='webgl'){var ctx=canvas.getContext(spec.id,spec.attributes||{alpha:false,antialias:false,depth:true,powerPreference:'high-performance'});if(!ctx)throw error('GFX-CONTEXT','Context request returned null.');return{canvas:canvas,context:ctx,id:spec.id};}if(spec.id==='webgpu'){if(!navigator.gpu)throw error('GFX-NOAPI','WebGPU API unavailable.');return navigator.gpu.requestAdapter({powerPreference:'high-performance'}).then(function(adapter){if(!adapter)throw error('GFX-ADAPTER','No WebGPU adapter.');return adapter.requestDevice(spec.deviceDescriptor||{}).then(function(device){var context=canvas.getContext('webgpu');if(!context){device.destroy();throw error('GFX-CONTEXT','WebGPU canvas unavailable.');}context.configure({device:device,format:navigator.gpu.getPreferredCanvasFormat(),alphaMode:'opaque'});return{id:'webgpu',canvas:canvas,context:context,device:device,adapter:adapter};});});}if(spec.id==='canvas2d'){var c=canvas.getContext('2d');if(!c)throw error('GFX-CONTEXT','2D canvas unavailable.');return{id:'canvas2d',canvas:canvas,context:c};}throw error('GFX-CONFIG','Unknown renderer identifier: '+spec.id);
  },Math.min(5000,Math.max(100,spec.timeoutMs||5000))).then(function(handle){if(b.failed){release(handle);throw error('BOOT-CANCELLED','Selection stopped.');}attempt.status='selected';b.graphics=handle;b.graphicsSpec=spec;handle.canvas.id='sb-graphics';document.body.appendChild(handle.canvas);b.report.renderer.selected=spec.id;text('sb-renderer',spec.id==='webgl2'?'WebGL 2 / GLSL ES 3.00':spec.id);handle.canvas.addEventListener('webglcontextlost',function(e){e.preventDefault();b.fail('GPU-LOST','The graphics context was lost. Reload to initialize a new context.');});if(handle.device)handle.device.lost.then(function(info){b.fail('GPU-LOST',info.message||'WebGPU device lost.');});return handle;},function(e){attempt.status='failed';attempt.reason=scrub(e.message);b.record('warn','GFX-FALLBACK',spec.id+': '+e.message);return next();});}
  return next();
 };
 Boot.prototype.checkLimits=function(){var h=this.graphics,gl=h.context,r=this.report.renderer,limits={};if(h.id==='webgl2'||h.id==='webgl'){var names=['MAX_TEXTURE_SIZE','MAX_RENDERBUFFER_SIZE','MAX_TEXTURE_IMAGE_UNITS','MAX_VERTEX_TEXTURE_IMAGE_UNITS','MAX_COMBINED_TEXTURE_IMAGE_UNITS','MAX_DRAW_BUFFERS','MAX_COLOR_ATTACHMENTS'];for(var i=0;i<names.length;i++){var n=names[i];if(gl[n]!==undefined)limits[n]=gl.getParameter(gl[n]);}limits.MAX_VIEWPORT_DIMS=Array.prototype.slice.call(gl.getParameter(gl.MAX_VIEWPORT_DIMS));r.version=gl.getParameter(gl.VERSION);r.shadingLanguage=gl.getParameter(gl.SHADING_LANGUAGE_VERSION);r.contextAttributes=gl.getContextAttributes();var dbg=null;try{dbg=gl.getExtension('WEBGL_debug_renderer_info');}catch(e){}r.adapter=dbg?gl.getParameter(dbg.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER);r.vendor=dbg?gl.getParameter(dbg.UNMASKED_VENDOR_WEBGL):gl.getParameter(gl.VENDOR);r.adapterDetail=dbg?'browser reported':'privacy-limited';r.limits=limits;text('sb-adapter',r.adapter||'Unavailable / not reported');r.fragmentHighPrecision=gl.getShaderPrecisionFormat(gl.FRAGMENT_SHADER,gl.HIGH_FLOAT).precision;var required=this.graphicsSpec.limits||{};for(var k in required)if(own(required,k)&&!(limits[k]>=required[k]))throw error('GFX-LIMIT',k+' requires '+required[k]+'; device reports '+limits[k]+'.');if(r.fragmentHighPrecision===0)throw error('GFX-PRECISION','High-precision fragment arithmetic is required.');r.limits=limits;
  }else if(h.id==='webgpu'){var info=h.adapter.info;r.adapter=info?(info.description||info.device||info.vendor||'Adapter details withheld'):'Adapter details withheld';r.limits={};}else r.adapter='Browser 2D canvas';text('sb-adapter',r.adapter||'Unavailable / not reported');if(this.graphicsSpec.validate)this.graphicsSpec.validate(h,this);
 };
 Boot.prototype.probe=function(){var b=this,h=this.graphics;if(this.graphicsSpec.probe)return this.graphicsSpec.probe(h,this);if(h.id==='webgpu'){var d=h.device;d.pushErrorScope('validation');var enc=d.createCommandEncoder(),pass=enc.beginRenderPass({colorAttachments:[{view:h.context.getCurrentTexture().createView(),clearValue:{r:.2,g:.6,b:.8,a:1},loadOp:'clear',storeOp:'store'}]});pass.end();d.queue.submit([enc.finish()]);return d.queue.onSubmittedWorkDone().then(function(){return d.popErrorScope();}).then(function(e){if(e)throw error('GFX-TEST',e.message);b.report.renderer.selfTest='GPU clear submitted and completed';});}if(h.id==='canvas2d'){h.context.fillStyle='#3399cc';h.context.fillRect(0,0,2,2);h.context.getImageData(0,0,1,1);this.report.renderer.selfTest='2D draw / read passed';return;}
  var gl=h.context,is2=h.id==='webgl2',program=null,shaders=[],tex=null,fbo=null,buffer=null,vao=null;try{function shader(type,source){var s=gl.createShader(type);if(!s)throw error('GFX-ALLOC','Could not allocate a shader.');shaders.push(s);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw error('GFX-SHADER',gl.getShaderInfoLog(s)||'Probe shader did not compile.');return s;}
   program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,is2?'#version 300 es\nvoid main(){vec2 p=vec2(float((gl_VertexID<<1)&2),float(gl_VertexID&2));gl_Position=vec4(p*2.-1.,0.,1.);}':'attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,is2?'#version 300 es\nprecision highp float;out vec4 c;void main(){c=vec4(.2,.6,.8,1.);}':'precision highp float;void main(){gl_FragColor=vec4(.2,.6,.8,1.);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw error('GFX-LINK',gl.getProgramInfoLog(program));tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,2,2,0,gl.RGBA,gl.UNSIGNED_BYTE,null);fbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,fbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,tex,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw error('GFX-TARGET','Probe framebuffer is incomplete.');if(is2){vao=gl.createVertexArray();gl.bindVertexArray(vao);}else{buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);var loc=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);}gl.viewport(0,0,2,2);gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.useProgram(program);gl.drawArrays(gl.TRIANGLES,0,3);var px=new Uint8Array(4);gl.readPixels(0,0,1,1,gl.RGBA,gl.UNSIGNED_BYTE,px);var er=gl.getError();if(er!==gl.NO_ERROR||Math.abs(px[0]-51)>2||Math.abs(px[1]-153)>2||Math.abs(px[2]-204)>2||px[3]!==255)throw error('GFX-PIXEL','Draw/read test failed. GL code '+er+'; pixel '+Array.prototype.join.call(px,',')+'.');this.report.renderer.selfTest='Shader / framebuffer / draw / pixel check passed';
  }finally{gl.useProgram(null);gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.bindTexture(gl.TEXTURE_2D,null);if(is2)gl.bindVertexArray(null);if(program)gl.deleteProgram(program);shaders.forEach(function(s){gl.deleteShader(s);});if(tex)gl.deleteTexture(tex);if(fbo)gl.deleteFramebuffer(fbo);if(buffer)gl.deleteBuffer(buffer);if(vao)gl.deleteVertexArray(vao);gl.viewport(0,0,16,16);}
 };
 Boot.prototype.optionalChecks=function(){var c=this.report.capabilities,gl=this.graphics.context;c.audio=!!(global.AudioContext||global.webkitAudioContext);c.fullscreen=this.screen.supported();c.wakeLock=!!(global.isSecureContext&&navigator.wakeLock&&navigator.wakeLock.request);c.orientationLock=!!(screen.orientation&&screen.orientation.lock);c.download=!!(global.Blob&&global.URL&&URL.createObjectURL);c.clipboard=!!(navigator.clipboard&&navigator.clipboard.writeText);c.webgpuAPI=!!navigator.gpu;c.localStorage=false;c.sessionStorage=false;try{localStorage.setItem('bootkit.probe','1');localStorage.removeItem('bootkit.probe');c.localStorage=true;}catch(e){this.optional('OPT-STORE','Local storage unavailable; settings may not persist.');}try{sessionStorage.setItem('bootkit.probe','1');sessionStorage.removeItem('bootkit.probe');c.sessionStorage=true;}catch(e){this.optional('OPT-SESSION','Session storage unavailable; interrupted stages cannot be retained.');}
  if(this.graphics.id.indexOf('webgl')===0){c.hdr=!!gl.getExtension('EXT_color_buffer_float');c.gpuTiming=!!gl.getExtension('EXT_disjoint_timer_query_webgl2');c.parallelShaders=!!gl.getExtension('KHR_parallel_shader_compile');if(!c.hdr)this.optional('OPT-HDR','Float render targets unavailable. Use the engine LDR / inline-reflection fallback.');if(!c.gpuTiming)this.optional('OPT-TIMER','GPU timer unavailable. GPU measurements remain N/A.');}
  if(!c.audio)this.optional('OPT-AUDIO','Audio unavailable. The game can run silently.');if(!c.fullscreen)this.optional('OPT-FULL','Fullscreen unavailable. Window play remains available.');if(!c.wakeLock)this.optional('OPT-WAKE','Screen wake lock unavailable in this context.');if(!c.orientationLock)this.optional('OPT-ROTATE','Orientation lock unavailable. Use device rotation controls.');var entries=[['Sound',c.audio],['Fullscreen API',c.fullscreen],['Screen wake lock',c.wakeLock],['Orientation lock API',c.orientationLock],['Saved settings',c.localStorage],['Session checkpoint',c.sessionStorage],['HDR float targets',c.hdr],['GPU timing',c.gpuTiming],['Parallel shader API',c.parallelShaders]].map(function(a){return a[0]+': '+(a[1]?'available':'unavailable');});entries.push('WebGPU: '+(c.webgpuAPI?'API exposed':'API unavailable')+'; selected renderer: '+this.report.renderer.selected);entries.push('Availability does not guarantee permission. Missing optional features do not block launch.');text('sb-optionalList',entries.join('\n'));
 };
 Boot.prototype.launch=function(full){if(this.failed||this.engineStarted||this.report.status!=='ready')return;this.engineStarted=true;el('sb-startGame').disabled=el('sb-startWindow').disabled=true;this.screen.orientation=el('sb-orientation').value;this.screen.keepAwake=el('sb-wake').checked;
  // Fullscreen MUST be requested in the originating user gesture, before awaits.
  var permission=full?this.screen.enter():Promise.resolve();var b=this;Promise.resolve(permission).catch(function(e){b.optional('MODE-REQUEST',e.message);}).then(function(){if(b.failed)return;b.phase='engine';b.current='L10';el('sb-ready').hidden=true;el('sb-stop').hidden=false;text('sb-title','Starting the engine');text('sb-subtitle','The graphics device is ready. Required game systems initialize next.');return b.run('L10','Game code',function(){return b.config.load(b);},30000);}).then(function(){if(b.failed)return;if(!b.pendingEngine)throw error('LOAD-CONTRACT','The game did not register an initializer.');return b.pendingEngine(b);}).catch(function(e){if(!b.failed)b.fail(e.bootCode||'LOAD-FAIL',e);});
 };
 Boot.prototype.register=function(fn){if(typeof fn!=='function')throw error('LOAD-CONTRACT','Initializer must be a function.');this.pendingEngine=fn;};
 Boot.prototype.readyToRun=function(hooks){if(this.failed)throw error('BOOT-CANCELLED','Cannot start the game after failure.');if(this.report.stages.length!==14||this.report.stages.some(function(s){return s.status!=='pass'&&s.status!=='warn';}))throw error('LOOP-GATE','All fourteen startup stages must complete before the loop can start.');this.hooks=hooks||{};if(!this.hooks.start)throw error('LOOP-CONTRACT','No game-loop start hook.');this.running=true;this.loaded=true;this.busy=false;this.phase='runtime';this.current='RUN';this.report.stage='RUN';this.report.status='running';this.report.startupMs=Math.round(now()-this.startedAt);this.report.startedGameAt=new Date().toISOString();this.report.workMs=this.report.stages.reduce(function(a,s){return a+(s.durationMs||0);},0);this.report.userWaitIncludedInStartupMs=true;this.checkpoint('running');el('sb-progress').value=100;text('sb-stage','RUN / FIRST FRAME VERIFIED');el('sb-stop').hidden=true;this.record('info','RUN','Main loop released after all required stages passed.');document.documentElement.classList.remove('sb-start');this.host.hidden=true;this.screen.sync();this.hooks.start();};
 Boot.prototype.openDiagnostics=function(){if(this.running){this.screen.pause('Startup report');this.host.hidden=false;text('sb-title','Startup report');text('sb-subtitle','Saved startup stages. The game is paused behind this screen.');el('sb-ready').hidden=true;el('sb-stop').hidden=true;el('sb-retry').hidden=false;var back=el('sb-backGame'),b=this;if(!back){back=document.createElement('button');back.id='sb-backGame';back.textContent='Back to game';back.className='sb-primary';el('sb-actionFooter').querySelector('.sb-actions').insertBefore(back,el('sb-copy'));back.onclick=function(){b.host.hidden=true;b.screen.resumeOverlay();};}back.hidden=false;}else this.host.hidden=false;};
 function ScreenMode(boot){this.boot=boot;this.requested=false;this.entering=false;this.fullscreen=false;this.orientation='auto';this.keepAwake=true;this.wake=null;this.wakeAttempt=0;this.wakePending=false;this.wakeStatus='not requested';this.orientationStatus='auto';this.fullStatus='window';this.token=0;this.orientationToken=0;this.overlayState=null;this.message='';var m=this;
  document.addEventListener('fullscreenchange',function(){m.changed();});document.addEventListener('webkitfullscreenchange',function(){m.changed();});
  document.addEventListener('visibilitychange',function(){if(document.hidden){m.leave('App or tab hidden');m.pause('App or tab hidden');}});global.addEventListener('pagehide',function(){m.leave('Page closed');});
  document.addEventListener('keydown',function(e){if(e.key==='Escape'&&m.requested){m.leave('Game mode exited');m.pause('Game mode exited');e.stopImmediatePropagation();}if(e.key==='Escape'&&el('sb-mode')&&!el('sb-mode').hidden){m.close();e.stopImmediatePropagation();}},true);
 }
 ScreenMode.prototype.supported=function(){var e=document.documentElement;return !!((e.requestFullscreen&&document.fullscreenEnabled!==false)||(e.webkitRequestFullscreen&&document.webkitFullscreenEnabled!==false));};
 ScreenMode.prototype.isFull=function(){return !!(document.fullscreenElement||document.webkitFullscreenElement);};
 ScreenMode.prototype.snapshot=function(){return {requested:this.requested,fullscreen:this.isFull(),status:this.fullStatus,wakeLock:this.wakeStatus,orientationRequested:this.orientation,orientationStatus:this.orientationStatus,keepAwake:this.keepAwake,viewport:[innerWidth,innerHeight],systemServicesBlocked:false};};
 ScreenMode.prototype.notice=function(s){this.message=s;text('sb-modeMessage',s);text('sb-footer',s);if(this.boot.hooks.notice)this.boot.hooks.notice(s);};
 ScreenMode.prototype.pause=function(reason){if(this.boot.hooks.pause){var state=this.boot.hooks.pause(reason);if(!this.overlayState)this.overlayState=state;if(/exited|hidden/.test(reason)&&this.overlayState)this.overlayState.wasPaused=true;}};
 ScreenMode.prototype.resumeOverlay=function(){if(this.overlayState&&this.boot.hooks.resume)this.boot.hooks.resume(this.overlayState);this.overlayState=null;};
 ScreenMode.prototype.enter=function(){var m=this,t=++this.token;this.requested=true;this.entering=true;this.fullStatus='requesting';document.documentElement.classList.add('sb-game-focus');this.sync();var request=null;try{var elem=document.documentElement,method=elem.requestFullscreen||elem.webkitRequestFullscreen;if(method)request=method.call(elem,{navigationUI:'hide'});else throw error('MODE-NOAPI','Fullscreen is not available. Game mode will use the window.');}catch(e){this.fullStatus='focus only';this.boot.optional('MODE-FULL',e.message);this.notice('Window game mode. Fullscreen is unavailable; system gestures still work.');}
  return new Promise(function(resolve){var done=false,timer=setTimeout(finish,2200);function finish(){if(done)return;done=true;clearTimeout(timer);if(t!==m.token){resolve();return;}m.entering=false;m.fullscreen=m.isFull();m.fullStatus=m.fullscreen?'fullscreen':'focus only';if(!m.fullscreen&&request)m.notice('Fullscreen was not granted. The game will start in the window.');m.applyOrientation();m.acquireWake();m.sync();m.boot.record('info','MODE-ENTER',m.fullStatus);resolve();}if(request&&request.then)request.then(function(){if(t!==m.token){if(m.isFull())m.leave('Late request cancelled');return;}finish();},function(e){m.boot.optional('MODE-FULL',e.message||'Fullscreen request rejected.');finish();});else finish();});
 };
 ScreenMode.prototype.acquireWake=function(){var m=this,t=this.token;if(!this.requested||!this.keepAwake||document.hidden||this.wake||this.wakePending)return;if(!global.isSecureContext||!navigator.wakeLock||!navigator.wakeLock.request){this.wakeStatus='unavailable';this.sync();return;}var wt=++this.wakeAttempt;this.wakePending=true;this.wakeStatus='requesting';var request;try{request=navigator.wakeLock.request('screen');}catch(e){this.wakePending=false;this.wakeStatus='not granted';this.boot.optional('MODE-WAKE',e.message);this.sync();return;}Promise.resolve(request).then(function(lock){if(wt!==m.wakeAttempt||t!==m.token||!m.requested||!m.keepAwake||document.hidden){try{var p=lock.release();if(p&&p.catch)p.catch(function(){});}catch(e){}return;}m.wakePending=false;m.wake=lock;m.wakeStatus='held';lock.addEventListener('release',function(){if(m.wake===lock){m.wake=null;m.wakeStatus='released by system';m.sync();}});m.sync();},function(e){if(wt!==m.wakeAttempt||t!==m.token)return;m.wakePending=false;m.wakeStatus='not granted';m.boot.optional('MODE-WAKE',e.message);m.sync();});};
 ScreenMode.prototype.releaseWake=function(){var w=this.wake;this.wakeAttempt++;this.wakePending=false;this.wake=null;this.wakeStatus='released';if(w)try{var p=w.release();if(p&&p.catch)p.catch(function(){});}catch(e){}};
 ScreenMode.prototype.applyOrientation=function(){var m=this,t=this.token,ot=++this.orientationToken,wanted=this.orientation,o=screen.orientation;try{if(!this.requested||this.orientation==='auto'){if(o&&o.unlock)o.unlock();this.orientationStatus='auto';this.sync();return;}if(!o||!o.lock){this.orientationStatus='unavailable';this.sync();return;}this.orientationStatus='requesting';Promise.resolve(o.lock(wanted)).then(function(){if(t!==m.token||!m.requested){if(o.unlock)o.unlock();return;}if(ot!==m.orientationToken){if(m.orientation==='auto'&&o.unlock)o.unlock();return;}m.orientationStatus='locked '+wanted;m.sync();},function(e){if(t!==m.token||ot!==m.orientationToken)return;m.orientationStatus='not granted';m.boot.optional('MODE-ORIENT',e.message);m.sync();});}catch(e){this.orientationStatus='not granted';this.sync();}};
 ScreenMode.prototype.leave=function(reason){var was=this.requested;this.token++;this.orientationToken++;this.requested=false;this.entering=false;document.documentElement.classList.remove('sb-game-focus');this.releaseWake();try{if(screen.orientation&&screen.orientation.unlock)screen.orientation.unlock();}catch(e){}this.orientationStatus='auto';this.fullStatus='window';if(this.isFull()){try{var f=document.exitFullscreen||document.webkitExitFullscreen,p=f&&f.call(document);if(p&&p.catch)p.catch(function(){});}catch(e){}}
  this.fullscreen=false;if(was)this.boot.record('info','MODE-EXIT',reason||'Game mode exited');this.sync();};
 ScreenMode.prototype.changed=function(){var full=this.isFull();if(this.entering){this.fullscreen=full;this.sync();return;}if(this.requested&&!full){this.leave('Fullscreen exited');this.pause('Fullscreen exited');this.notice('Game mode ended. The game is paused.');}else{this.fullscreen=full;this.sync();}};
 ScreenMode.prototype.toggle=function(){if(this.requested){this.leave('Player exited game mode');this.pause('Game mode exited');this.notice('Game mode ended. Resume when ready.');return Promise.resolve();}return this.enter();};
 ScreenMode.prototype.sync=function(){this.fullscreen=this.isFull();text('sb-modeState',this.requested?(this.fullscreen?'Fullscreen game mode':'Window game mode — not fullscreen'):'Window mode');text('sb-wakeState',this.wakeStatus);text('sb-orientState',this.orientationStatus);text('sb-modeToggle',this.requested?'Exit game mode':'Enter fullscreen / game mode');text('sb-modeMessage',this.message||'System gestures and app switching remain available.');if(this.boot.hooks.screenChanged)this.boot.hooks.screenChanged(this.snapshot());};
 ScreenMode.prototype.open=function(){var m=this;this.pause('Display settings');var panel=el('sb-mode');if(!panel){panel=document.createElement('section');panel.id='sb-mode';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','Fullscreen and game mode');panel.innerHTML='<div class="sb-card"><div class="sb-top"><span class="sb-over">DISPLAY / GAME MODE</span><button id="sb-modeClose">Close</button></div><h1>Fullscreen / game mode</h1><p>Hide browser controls where supported. Keep the screen awake during play. Exit restores normal page behaviour.</p><dl class="sb-facts"><dt>Mode</dt><dd id="sb-modeState"></dd><dt>Screen awake</dt><dd id="sb-wakeState"></dd><dt>Orientation</dt><dd id="sb-orientState"></dd></dl><div class="sb-options"><label>Orientation <select id="sb-modeOrient"><option value="auto">Auto rotate</option><option value="landscape">Landscape</option><option value="portrait">Portrait</option></select></label><label><input type="checkbox" id="sb-modeWake"> Keep screen awake</label></div><div class="sb-actions"><button class="sb-primary" id="sb-modeToggle">Enter fullscreen / game mode</button><button id="sb-modeBoot">Startup diagnostics</button></div><p id="sb-modeMessage" role="status"></p><p class="sb-small">This web page cannot disable notifications, calls, system navigation, app switching, or background services. Page gestures are reduced in game mode. Device edge gestures can still exit.</p><p class="sb-small">The game pauses on exit or app switch. Use the visible exit control, the browser fullscreen control, or Escape on a keyboard. No keyboard or navigation traps are used.</p></div>';document.body.appendChild(panel);el('sb-modeClose').onclick=function(){m.close();};el('sb-modeToggle').onclick=function(){m.toggle();};el('sb-modeBoot').onclick=function(){panel.hidden=true;m.boot.openDiagnostics();};el('sb-modeOrient').onchange=function(){m.orientation=this.value;m.applyOrientation();};el('sb-modeWake').onchange=function(){m.keepAwake=this.checked;if(this.checked)m.acquireWake();else m.releaseWake();m.sync();};}panel.hidden=false;el('sb-modeOrient').value=this.orientation;el('sb-modeWake').checked=this.keepAwake;this.sync();el('sb-modeClose').focus();};
 ScreenMode.prototype.close=function(){if(el('sb-mode'))el('sb-mode').hidden=true;this.resumeOverlay();};
 global.BootKit={version:VERSION,create:function(c){return new Boot(c);},error:error};
})(window);
